# Generated by Django 6.0.4 on 2026-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'សាច់ប្រាក់'), ('khqr', 'KHQR / ធនាគារ')], default='cash', max_length=10),
        ),
    ]
